package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// verbGroup renders verbs as a regex alternation, e.g. "(delete|emit|void)".
func verbGroup(verbs []string) string {
	return "(" + strings.Join(verbs, "|") + ")"
}

// --- Claude Code ---

func emitClaudeCode(cmd *cobra.Command, g guardPlan, write bool) error {
	blocked := g.blockedVerbs()
	asked := distinctVerbs(g.asked())

	deny := []string{}
	for _, v := range blocked {
		deny = append(deny, fmt.Sprintf("Bash(alegra * %s:*)", v))
	}
	if len(blocked) > 0 {
		deny = append(deny, "mcp__.*alegra.*_"+verbGroup(blocked))
	}
	ask := []string{}
	for _, v := range asked {
		ask = append(ask, fmt.Sprintf("Bash(alegra * %s:*)", v))
	}
	if len(asked) > 0 {
		ask = append(ask, "mcp__.*alegra.*_"+verbGroup(asked))
	}

	hookPath := "${CLAUDE_PROJECT_DIR}/.claude/hooks/alegra-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookPath}},
		}
	}
	settings := map[string]any{
		"permissions": map[string]any{"deny": deny, "ask": ask},
		"hooks": map[string]any{
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__.*alegra.*")},
		},
	}
	settingsJSON, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}

	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Claude Code agent-safety config. The MCP-tool branch of the hook is a hard")
	fmt.Fprintln(out, "# block (structured tool names can't be obfuscated); the Bash branch is")
	fmt.Fprintln(out, "# best-effort — it defeats quote/backslash tricks but not variable")
	fmt.Fprintln(out, "# indirection or shell aliases, so MCP-only operation (or a read-only")
	fmt.Fprintln(out, "# sandbox) is the strongest guarantee. The permission rules are")
	fmt.Fprintln(out, "# belt-and-suspenders. Regenerate after upgrading.")
	fmt.Fprintln(out)
	if err := writeOrPrint(cmd, write, hookScriptPath(write), claudeHookScript(blocked), 0o755); err != nil {
		return err
	}
	fmt.Fprintln(out)
	return writeOrPrint(cmd, write, claudeSettingsPath(write), string(settingsJSON)+"\n", 0o644)
}

func hookScriptPath(write bool) string {
	if write {
		return filepath.Join(".claude", "hooks", "alegra-guard.sh")
	}
	return ".claude/hooks/alegra-guard.sh"
}

func claudeSettingsPath(write bool) string {
	if write {
		return filepath.Join(".claude", "settings.json")
	}
	return ".claude/settings.json"
}

func claudeHookScript(blocked []string) string {
	return `#!/usr/bin/env bash
# alegra agent guard — blocks irreversible alegra operations on the Bash and MCP
# surfaces. Generated by ` + "`alegra agent guard`" + `; regenerate after
# upgrading alegra so new actions are covered.
#
# The MCP-tool branch is a hard block. The Bash branch is best-effort: it defeats
# quote/backslash obfuscation (e.g. ` + "`alegra vo\"\"id`" + `) but NOT variable
# indirection (` + "`a=void; alegra $a`" + `) or shell aliases — run agents
# MCP-only or in a read-only sandbox for a hard guarantee.
verbs='` + verbGroup(blocked) + `'
input=$(cat)

# deny_raw emits a denial with a FIXED reason via printf (no jq, no interpolation
# → always valid JSON). Used by the no-jq fallback.
deny_raw() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}

# Without jq we cannot isolate the tool name. Fail safe, not open: scan the raw
# payload (newlines flattened) for an irreversible alegra verb and deny if
# present, rather than silently allowing everything.
if ! command -v jq >/dev/null 2>&1; then
  if printf '%s' "$input" | tr '\n' ' ' | grep -qiE "alegra.*${verbs}"; then
    deny_raw "alegra agent guard: irreversible operation blocked (jq unavailable; raw match)."
  fi
  exit 0
fi

# deny emits the denial with a jq-escaped reason, so an interpolated value (e.g.
# a tool name) can never break out of the JSON string.
deny() {
  jq -c -n --arg r "$1" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
case "$tool" in
  Bash)
    cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    # Also test with quotes/backslashes stripped to defeat trivial obfuscation
    # such as ` + "`alegra invoices vo\"\"id 1`" + ` (\042=" \047=' \134=\), and
    # flatten newlines so a verb split across lines can't slip past the
    # line-oriented grep.
    stripped=$(printf '%s' "$cmd" | tr -d '\042\047\134')
    if printf '%s\n%s' "$cmd" "$stripped" | tr '\n' ' ' | grep -qiE "\balegra\b.*\b${verbs}\b"; then
      deny "alegra agent guard: irreversible operation blocked (${verbs})."
    fi
    ;;
  mcp__*alegra*)
    if printf '%s' "$tool" | grep -qiE "_${verbs}$"; then
      deny "alegra agent guard: irreversible MCP tool blocked (${tool})."
    fi
    ;;
esac
exit 0
`
}

// --- Codex ---

func emitCodex(cmd *cobra.Command, g guardPlan, write bool) error {
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Codex agent-safety config (~/.codex/config.toml).")
	fmt.Fprintln(out, "# Codex has no per-command deny hook: read-only sandbox is the hard block,")
	fmt.Fprintln(out, "# and destructive MCP tools (which alegra annotates) already require approval.")
	fmt.Fprintln(out)
	mode := "read-only"
	policy := "untrusted"
	note := "# read-only sandbox: no alegra write can run without an explicit approval."
	if !g.allWrites {
		note = "# read-only sandbox + untrusted: writes pause for approval; reads run free.\n" +
			"# Switch sandbox_mode to \"workspace-write\" only if you accept unattended writes."
	}
	content := fmt.Sprintf("sandbox_mode    = %q\napproval_policy = %q\n\n%s\n", mode, policy, note)
	return writeOrPrint(cmd, write, codexConfigPath(write), content, 0o644)
}

func codexConfigPath(write bool) string {
	if write {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, ".codex", "config.toml")
		}
	}
	return "~/.codex/config.toml"
}

// --- OpenCode ---

func emitOpenCode(cmd *cobra.Command, g guardPlan, write bool) error {
	blocked := g.blockedVerbs()
	asked := distinctVerbs(g.asked())

	bash := map[string]any{"*": "allow"}
	perm := map[string]any{}
	for _, v := range blocked {
		bash["alegra * "+v+"*"] = "deny"
		perm["alegra_*_"+v] = "deny"
	}
	for _, v := range asked {
		bash["alegra * "+v+"*"] = "ask"
		perm["alegra_*_"+v] = "ask"
	}
	perm["bash"] = bash

	cfg := map[string]any{
		"$schema":    "https://opencode.ai/config.json",
		"permission": perm,
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# OpenCode agent-safety config (opencode.json). `deny` is a hard block;")
	fmt.Fprintln(out, "# `ask` prompts. The specific alegra patterns take precedence over the `*`")
	fmt.Fprintln(out, "# catch-all, which allows everything else.")
	fmt.Fprintln(out)
	return writeOrPrint(cmd, write, openCodeConfigPath(write), string(b)+"\n", 0o644)
}

func openCodeConfigPath(write bool) string {
	if write {
		return "opencode.json"
	}
	return "opencode.json"
}
