package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// verbGroup renders verbs as a regex alternation, e.g. "(delete|emit|void)".
func verbGroup(verbs []string) string {
	return "(" + strings.Join(verbs, "|") + ")"
}

// --- Claude Code ---

func emitClaudeCode(cmd *cobra.Command, g guardPlan, write bool) error {
	blocked := g.blocked()
	asked := g.asked()

	// Exact, non-regex deny rules — one entry per blocked command path.
	// Claude matches permission rules as literal prefix patterns, so
	// "Bash(alegra invoices void:*)" matches exactly that subcommand prefix
	// and cannot false-match an argument that happens to contain "void".
	deny := []string{}
	for _, gc := range blocked {
		deny = append(deny, fmt.Sprintf("Bash(alegra %s:*)", gc.cli))
	}
	// Exact MCP tool names — no regex, no glob (Claude permission rules do not
	// interpret regex, so a pattern like "mcp__.*alegra.*_(void|…)" never
	// matches anything). Each blocked command has a deterministic tool name
	// under the default server name (e.g. "mcp__alegra__alegra_invoices_void");
	// if the server was registered under a custom --server-name, the hook's
	// verb-suffix fallback still covers it.
	for _, gc := range blocked {
		deny = append(deny, "mcp__alegra__"+gc.tool)
	}

	ask := []string{}
	for _, gc := range asked {
		ask = append(ask, fmt.Sprintf("Bash(alegra %s:*)", gc.cli))
	}
	for _, gc := range asked {
		ask = append(ask, "mcp__alegra__"+gc.tool)
	}

	hookPath := "${CLAUDE_PROJECT_DIR}/.claude/hooks/alegra-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookPath}},
		}
	}
	settings := map[string]any{
		"permissions": map[string]any{"deny": deny, "ask": ask},
		"hooks": map[string]any{
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__.*alegra.*")},
		},
	}
	settingsJSON, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}

	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Claude Code agent-safety config. The MCP-tool branch of the hook is a hard")
	fmt.Fprintln(out, "# block (structured tool names can't be obfuscated); the Bash branch is")
	fmt.Fprintln(out, "# best-effort — it defeats quote/backslash tricks and path-prefixed")
	fmt.Fprintln(out, "# invocations (./bin/alegra) but not variable indirection or shell aliases,")
	fmt.Fprintln(out, "# so MCP-only operation (or a read-only sandbox) is the strongest guarantee.")
	fmt.Fprintln(out, "# The permission rules are belt-and-suspenders. Regenerate after upgrading.")
	fmt.Fprintln(out)
	if err := writeOrPrint(cmd, write, hookScriptPath(write), claudeHookScript(blocked), 0o755); err != nil {
		return err
	}
	fmt.Fprintln(out)
	return writeOrPrint(cmd, write, claudeSettingsPath(write), string(settingsJSON)+"\n", 0o644)
}

func hookScriptPath(write bool) string {
	if write {
		return filepath.Join(".claude", "hooks", "alegra-guard.sh")
	}
	return ".claude/hooks/alegra-guard.sh"
}

func claudeSettingsPath(write bool) string {
	if write {
		return filepath.Join(".claude", "settings.json")
	}
	return ".claude/settings.json"
}

// claudeHookScript generates the PreToolUse hook script. It uses exact
// command-path anchored matching rather than bare-verb grep so that arguments
// containing a blocked word do not cause false positives
// (e.g. `alegra invoices create --data '{"note":"delete later"}'` is allowed;
// only `alegra invoices delete` at the command position is blocked).
func claudeHookScript(blocked []guardCmd) string {
	// Build ordered, deduplicated lists: pre-escaped ERE fragments for the Bash
	// branch (escaped in Go so the script needs no sed at runtime) and exact
	// tool names for the MCP branch.
	seenCLI := map[string]bool{}
	seenTool := map[string]bool{}
	var cliPatterns []string
	var toolNames []string
	for _, gc := range blocked {
		if !seenCLI[gc.cli] {
			seenCLI[gc.cli] = true
			cliPatterns = append(cliPatterns, strings.ReplaceAll(gc.cli, " ", "[[:space:]]+"))
		}
		if !seenTool[gc.tool] {
			seenTool[gc.tool] = true
			toolNames = append(toolNames, "mcp__alegra__"+gc.tool)
		}
	}

	shellArray := func(name string, items []string) string {
		var b strings.Builder
		b.WriteString(name + "=(\n")
		for _, it := range items {
			// Escape any single quotes (there should be none, but be safe).
			b.WriteString("  '" + strings.ReplaceAll(it, "'", "'\\''") + "'\n")
		}
		b.WriteString(")")
		return b.String()
	}

	return `#!/usr/bin/env bash
# alegra agent guard — blocks irreversible alegra operations on the Bash and MCP
# surfaces. Generated by ` + "`alegra agent guard`" + `; regenerate after
# upgrading alegra so new actions are covered.
#
# MATCHING STRATEGY: commands are matched by exact SUBCOMMAND PATH at the
# command position, not by bare verbs anywhere in the line. This prevents:
#   - false positives: ` + "`alegra invoices create --data 'note: delete later'`" + `
#     is NOT blocked because "invoices create" is not in the blocked set.
#   - false negatives: the path is still found after ; | && and newlines.
#
# For each blocked cli-path P, we check whether the CLEANED command string
# matches the anchored ERE:
#   (^|[;&|([:space:]]+)([^[:space:]]*/)?alegra[[:space:]]+<P>([[:space:];&|)]|$)
# which ensures alegra+P appears at a command position. The optional
# ([^[:space:]]*/)? prefix also catches path-invoked binaries like
# ./bin/alegra or /usr/local/bin/alegra, while a different binary whose name
# merely ends in "alegra" (e.g. myalegra) is not matched.
#
# The MCP branch is an exact set-membership check on the default server name
# (mcp__alegra__…), with a verb-suffix fallback for servers registered under a
# custom --server-name. alegra has no raw-API escape command, so there is no
# HTTP-method branch.
#
# De-obfuscation: quotes (\042 / \047) and backslash (\134) are stripped from
# the raw command string before pattern matching to defeat trivial tricks like
#   alegra invoices vo""id 1
# A side effect is that a QUOTED blocked command in an argument (e.g.
#   rg "alegra invoices delete" src/
# ) is also denied — a deliberate, safe-direction false positive: quoting is
# exactly the obfuscation channel being closed. Variable indirection
# (a=void; alegra invoices $a 1) and aliases are NOT defeated — use MCP-only
# mode or a read-only sandbox for a hard guarantee.

# --- blocked command paths (Bash surface; pre-escaped ERE fragments) ---
` + shellArray("blocked_cmds", cliPatterns) + `

# --- blocked MCP tool names (exact, default server name) ---
` + shellArray("blocked_tools", toolNames) + `

# --- verb-suffix fallback for custom-named alegra MCP servers ---
verb_suffix='` + verbGroup(distinctVerbs(blocked)) + `'

input=$(cat)

# deny_raw emits a denial with a FIXED reason via printf (no jq, no interpolation
# → always valid JSON). Used by the no-jq fallback.
deny_raw() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"%s"}}\n' "$1"
  exit 0
}

# deobfuscate strips quote chars (\042=" \047=' \134=\) and collapses newlines
# to a single line so obfuscation tricks can't split a token across lines.
deobfuscate() {
  printf '%s' "$1" | tr -d '\042\047\134' | tr '\n' ' '
}

# bash_is_blocked returns 0 (true) if the cleaned command contains a blocked
# alegra subcommand at the command position.
bash_is_blocked() {
  local cleaned="$1"
  local pat
  for pat in "${blocked_cmds[@]}"; do
    if printf '%s' "$cleaned" | grep -qiE "(^|[;&|([:space:]]+)([^[:space:]]*/)?alegra[[:space:]]+${pat}([[:space:];&|)]|\$)"; then
      return 0
    fi
  done
  return 1
}

# mcp_is_blocked returns 0 (true) for a blocked MCP tool: exact set-membership
# first, then the verb-suffix fallback for any alegra-named server.
mcp_is_blocked() {
  local tool="$1"
  local t
  for t in "${blocked_tools[@]}"; do
    if [ "$tool" = "$t" ]; then
      return 0
    fi
  done
  case "$tool" in
    mcp__*alegra*)
      if printf '%s' "$tool" | grep -qiE "_${verb_suffix}$"; then
        return 0
      fi
      ;;
  esac
  return 1
}

# Without jq we cannot isolate the tool_name/command fields. Fail safe: apply
# the same de-obfuscation and anchored path matching on the raw payload. JSON
# punctuation is converted to spaces first because quote-stripping glues the
# payload into command:alegra…, which would hide the command position from the
# anchored pattern (fail-open). This makes the no-jq branch slightly MORE
# conservative than the jq branch — acceptable for a degraded fallback.
if ! command -v jq >/dev/null 2>&1; then
  flat=$(printf '%s' "$input" | tr '\n' ' ')
  cleaned=$(deobfuscate "$flat" | tr '{}:,' '    ')
  if bash_is_blocked "$cleaned"; then
    deny_raw "alegra agent guard: irreversible operation blocked (jq unavailable; raw match)."
  fi
  # MCP payloads carry the tool name inline; catch blocked-verb alegra tools.
  if printf '%s' "$cleaned" | grep -qiE "mcp__[^[:space:]]*alegra[^[:space:]]*_${verb_suffix}([^[:alnum:]_-]|\$)"; then
    deny_raw "alegra agent guard: irreversible MCP tool blocked (jq unavailable; raw match)."
  fi
  exit 0
fi

# deny emits the denial with a jq-escaped reason, so an interpolated value (e.g.
# a tool name) can never break out of the JSON string.
deny() {
  jq -c -n --arg r "$1" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
case "$tool" in
  Bash)
    raw_cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    cleaned=$(deobfuscate "$raw_cmd")
    if bash_is_blocked "$cleaned"; then
      deny "alegra agent guard: irreversible operation blocked."
    fi
    ;;
  *)
    if mcp_is_blocked "$tool"; then
      deny "alegra agent guard: irreversible MCP tool blocked (${tool})."
    fi
    ;;
esac
exit 0
`
}

// --- Codex ---

func emitCodex(cmd *cobra.Command, g guardPlan, write bool) error {
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Codex agent-safety config (~/.codex/config.toml).")
	fmt.Fprintln(out, "# Codex has no per-command deny hook: read-only sandbox is the hard block,")
	fmt.Fprintln(out, "# and destructive MCP tools (which alegra annotates) already require approval.")
	fmt.Fprintln(out)
	mode := "read-only"
	policy := "untrusted"
	note := "# read-only sandbox: no alegra write can run without an explicit approval."
	if !g.allWrites {
		note = "# read-only sandbox + untrusted: writes pause for approval; reads run free.\n" +
			"# Switch sandbox_mode to \"workspace-write\" only if you accept unattended writes."
	}
	content := fmt.Sprintf("sandbox_mode    = %q\napproval_policy = %q\n\n%s\n", mode, policy, note)
	return writeOrPrint(cmd, write, codexConfigPath(write), content, 0o644)
}

func codexConfigPath(write bool) string {
	if write {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, ".codex", "config.toml")
		}
	}
	return "~/.codex/config.toml"
}

// --- OpenCode ---

func emitOpenCode(cmd *cobra.Command, g guardPlan, write bool) error {
	blocked := g.blocked()
	asked := g.asked()

	// Exact per-command rules — no mid-pattern verb globs. "alegra * void*"
	// could false-match an argument containing "void", and a glob MCP key like
	// "alegra_*_void" misses compound tool names; one exact rule per command
	// cannot do either.
	bash := map[string]any{"*": "allow"}
	perm := map[string]any{}
	for _, gc := range blocked {
		bash["alegra "+gc.cli] = "deny"
		perm[gc.tool] = "deny"
	}
	for _, gc := range asked {
		bash["alegra "+gc.cli] = "ask"
		perm[gc.tool] = "ask"
	}
	perm["bash"] = bash

	cfg := map[string]any{
		"$schema":    "https://opencode.ai/config.json",
		"permission": perm,
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# OpenCode agent-safety config (opencode.json). `deny` is a hard block;")
	fmt.Fprintln(out, "# `ask` prompts. Exact per-command rules take precedence over the `*`")
	fmt.Fprintln(out, "# catch-all, which allows everything else.")
	fmt.Fprintln(out)
	return writeOrPrint(cmd, write, openCodeConfigPath(write), string(b)+"\n", 0o644)
}

func openCodeConfigPath(write bool) string {
	if write {
		return "opencode.json"
	}
	return "opencode.json"
}
