package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// verbGroup renders verbs as a regex alternation, e.g. "(delete|emit|void)".
func verbGroup(verbs []string) string {
	return "(" + strings.Join(verbs, "|") + ")"
}

// --- Claude Code ---

func emitClaudeCode(cmd *cobra.Command, g guardPlan, write bool) error {
	blocked := g.blockedVerbs()
	asked := distinctVerbs(g.asked())

	deny := []string{}
	for _, v := range blocked {
		deny = append(deny, fmt.Sprintf("Bash(alegra * %s:*)", v))
	}
	if len(blocked) > 0 {
		deny = append(deny, "mcp__.*alegra.*_"+verbGroup(blocked))
	}
	ask := []string{}
	for _, v := range asked {
		ask = append(ask, fmt.Sprintf("Bash(alegra * %s:*)", v))
	}
	if len(asked) > 0 {
		ask = append(ask, "mcp__.*alegra.*_"+verbGroup(asked))
	}

	hookPath := "${CLAUDE_PROJECT_DIR}/.claude/hooks/alegra-guard.sh"
	hookEntry := func(matcher string) map[string]any {
		return map[string]any{
			"matcher": matcher,
			"hooks":   []any{map[string]any{"type": "command", "command": hookPath}},
		}
	}
	settings := map[string]any{
		"permissions": map[string]any{"deny": deny, "ask": ask},
		"hooks": map[string]any{
			"PreToolUse": []any{hookEntry("Bash"), hookEntry("mcp__.*alegra.*")},
		},
	}
	settingsJSON, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}

	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Claude Code agent-safety config. The hook is the definitive block")
	fmt.Fprintln(out, "# (it inspects the real command/tool, so glob tricks can't bypass it);")
	fmt.Fprintln(out, "# the permission rules are belt-and-suspenders. Regenerate after upgrading.")
	fmt.Fprintln(out)
	if err := writeOrPrint(cmd, write, hookScriptPath(write), claudeHookScript(blocked), 0o755); err != nil {
		return err
	}
	fmt.Fprintln(out)
	return writeOrPrint(cmd, write, claudeSettingsPath(write), string(settingsJSON)+"\n", 0o644)
}

func hookScriptPath(write bool) string {
	if write {
		return filepath.Join(".claude", "hooks", "alegra-guard.sh")
	}
	return ".claude/hooks/alegra-guard.sh"
}

func claudeSettingsPath(write bool) string {
	if write {
		return filepath.Join(".claude", "settings.json")
	}
	return ".claude/settings.json"
}

func claudeHookScript(blocked []string) string {
	return `#!/usr/bin/env bash
# alegra agent guard — definitively blocks irreversible alegra operations on the
# Bash and MCP surfaces. Generated by ` + "`alegra agent guard`" + `; regenerate
# after upgrading alegra so new actions are covered.
verbs='` + verbGroup(blocked) + `'
input=$(cat)
tool=$(printf '%s' "$input" | jq -r '.tool_name // empty')
deny() {
  jq -n --arg r "$1" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}
case "$tool" in
  Bash)
    cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // empty')
    if printf '%s' "$cmd" | grep -qiE "\balegra\b.*\b${verbs}\b"; then
      deny "alegra agent guard: irreversible operation blocked (${verbs})."
    fi
    ;;
  mcp__*alegra*)
    if printf '%s' "$tool" | grep -qiE "_${verbs}$"; then
      deny "alegra agent guard: irreversible MCP tool blocked (${tool})."
    fi
    ;;
esac
exit 0
`
}

// --- Codex ---

func emitCodex(cmd *cobra.Command, g guardPlan, write bool) error {
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# Codex agent-safety config (~/.codex/config.toml).")
	fmt.Fprintln(out, "# Codex has no per-command deny hook: read-only sandbox is the hard block,")
	fmt.Fprintln(out, "# and destructive MCP tools (which alegra annotates) already require approval.")
	fmt.Fprintln(out)
	mode := "read-only"
	policy := "untrusted"
	note := "# read-only sandbox: no alegra write can run without an explicit approval."
	if !g.allWrites {
		note = "# read-only sandbox + untrusted: writes pause for approval; reads run free.\n" +
			"# Switch sandbox_mode to \"workspace-write\" only if you accept unattended writes."
	}
	content := fmt.Sprintf("sandbox_mode    = %q\napproval_policy = %q\n\n%s\n", mode, policy, note)
	return writeOrPrint(cmd, write, codexConfigPath(write), content, 0o644)
}

func codexConfigPath(write bool) string {
	if write {
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, ".codex", "config.toml")
		}
	}
	return "~/.codex/config.toml"
}

// --- OpenCode ---

func emitOpenCode(cmd *cobra.Command, g guardPlan, write bool) error {
	blocked := g.blockedVerbs()
	asked := distinctVerbs(g.asked())

	bash := map[string]any{"*": "allow"}
	perm := map[string]any{}
	for _, v := range blocked {
		bash["alegra * "+v+"*"] = "deny"
		perm["alegra_*_"+v] = "deny"
	}
	for _, v := range asked {
		bash["alegra * "+v+"*"] = "ask"
		perm["alegra_*_"+v] = "ask"
	}
	perm["bash"] = bash

	cfg := map[string]any{
		"$schema":    "https://opencode.ai/config.json",
		"permission": perm,
	}
	b, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	out := cmd.OutOrStdout()
	fmt.Fprintln(out, "# OpenCode agent-safety config (opencode.json). `deny` is a hard block;")
	fmt.Fprintln(out, "# `ask` prompts. The last matching pattern wins, so the catch-all is first.")
	fmt.Fprintln(out)
	return writeOrPrint(cmd, write, openCodeConfigPath(write), string(b)+"\n", 0o644)
}

func openCodeConfigPath(write bool) string {
	if write {
		return "opencode.json"
	}
	return "opencode.json"
}
